# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-20 04:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0002_auto_20171009_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario_creo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
