# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importacion',
            old_name='procesados',
            new_name='procesado',
        ),
        migrations.AlterField(
            model_name='importacion',
            name='importados_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
