# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importador', '0003_auto_20170203_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionInstituciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='importaciones')),
                ('procesado', models.BooleanField(default=False)),
                ('importados_num', models.PositiveIntegerField(default=0)),
                ('instituciones_creadas', models.PositiveIntegerField(default=0)),
                ('instituciones_actualizadas', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Importaciones de instiruciones',
                'verbose_name': 'Importacion de instituciones',
            },
        ),
    ]
