# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile-pictures/'),
        ),
    ]
