# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 15:59
from __future__ import unicode_literals

from django.contrib.auth.models import Group
from django.db import migrations

def create_invitado_group(apps, schema_editor):
    Group.objects.create(name='Invitado')
    print("Se creó el grupo: Invitado")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_user_imagen'),
    ]

    operations = [
        migrations.RunPython(create_invitado_group)
    ]
