# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 07:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}', 'Por favor agregué un número telefónico válido')])),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], max_length=15)),
                ('sector', models.CharField(max_length=45)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisores',
            },
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Básico', 'Básico'), ('Medio Superior', 'Medio Superior'), ('Superior', 'Superior')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='subnivel',
            field=models.CharField(blank=True, choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Licenciatura', 'Licenciatura'), ('Posgrado', 'Posgrado')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Equipo', 'Equipo'), ('Individual', 'Individual')], max_length=10, verbose_name='Tipo del proyecto'),
        ),
    ]
