# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_auto_20170111_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=11)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Días de clase',
                'verbose_name': 'Día de clase',
            },
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='horario',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='semestre',
            field=models.CharField(choices=[('1', 'Enero-Junio'), ('2', 'Agosto-Diciembre')], max_length=1),
        ),
        migrations.AddField(
            model_name='diaclase',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='escuela.Grupo'),
        ),
    ]
