# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_auto_20170112_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='escuela.Alumno'),
        ),
    ]
