# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_auto_20170112_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', 'Termino')], default='1', max_length=1),
        ),
    ]
