# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 05:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_auto_20170128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='informacionpersonal',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('[0-9]{7,10}', 'Por favor agregué un número telefónico válido')]),
        ),
    ]
