# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_auto_20170203_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaPractica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=11)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_practica', to='escuela.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Días de práctica',
                'verbose_name': 'Día de práctica',
            },
        ),
    ]
