# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0008_diapractica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='sector',
        ),
        migrations.AddField(
            model_name='institucion',
            name='sector',
            field=models.CharField(choices=[('Privado', 'Privado'), ('Público', 'Público')], default='Público', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diaclase',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=11),
        ),
        migrations.AlterField(
            model_name='diapractica',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=11),
        ),
        migrations.AlterField(
            model_name='diaspracticas',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado'), ('Domingo', 'Domingo')], max_length=11),
        ),
    ]
