# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0009_auto_20170607_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='apellido_paterno',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=65, verbose_name='Nombre(s)'),
        ),
    ]
