# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0011_grupo_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='escuela.Docente'),
        ),
    ]
