# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-01 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0012_auto_20170801_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
