# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0014_auto_20170803_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='tipo_seguro',
            field=models.CharField(blank=True, choices=[('Facultativo', 'Facultativo'), ('ICHISAL', 'ICHISAL'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('Pensiones', 'Pensiones'), ('Privado', 'Privado'), ('Seguro popular', 'Seguro popular')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nivel',
            field=models.CharField(blank=True, choices=[('Inicial', 'Inicial'), ('Básico', 'Básico'), ('Medio Superior', 'Medio Superior'), ('Superior', 'Superior')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='subnivel',
            field=models.CharField(blank=True, choices=[('Preescolar', 'Preescolar'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Formación técnica', 'Formación técnica'), ('Bachillerato', 'Bachillerato'), ('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado')], max_length=18, null=True),
        ),
    ]
