# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0015_auto_20170814_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='beneficiarios',
            field=models.CharField(blank=True, help_text='Categoría', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='beneficiarios_cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
