# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0016_auto_20170814_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='escuela.Alumno'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('Desarrollo de trayectos profesionales', 'Desarrollo de trayectos profesionales'), ('Emprendimiento', 'Emprendimiento'), ('Estadías Docentes', 'Estadías Docentes'), ('Independiente', 'Independiente'), ('Intervención Educativa', 'Intervención Educativa'), ('Proyecto Independiente', 'Proyecto Independiente')], max_length=37, null=True),
        ),
    ]
