# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0018_auto_20170823_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpersonal',
            name='tipo_seguro',
            field=models.CharField(blank=True, choices=[('Facultativo', 'Facultativo'), ('ICHISAL', 'ICHISAL'), ('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE'), ('Pensiones', 'Pensiones'), ('Privado', 'Privado'), ('Seguro popular', 'Seguro popular')], max_length=15, null=True),
        ),
    ]
