# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-31 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0019_auto_20170830_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaalumno',
            name='nota',
            field=models.TextField(),
        ),
    ]
