# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0020_auto_20170831_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino'), ('Fin de semana', 'Fin de semana')], max_length=15),
        ),
    ]
