# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-05 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0021_auto_20170904_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='supervisores',
            field=models.ManyToManyField(blank=True, to='escuela.Supervisor'),
        ),
    ]
