# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0022_institucion_supervisores'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
